version: '3.8'
services:
  hugo:
    image: openmodelingfoundation/omf.io:latest
    build:
      context: .
      args:
        HUGO_VERSION: ${HUGO_VERSION}
    ports:
      - "127.0.0.1:1313:1313"
    volumes:
      - .:/src
      - /src/node_modules
