version: '3'
services:
  hugo:
    image: openmodelingfoundation/openmodelingfoundation.github.io:latest
    build: ./deploy
    ports:
      - "127.0.0.1:1313:1313"
    volumes:
      - .:/src
      - /src/node_modules
