name: vote
on:
  # trigger workflow on pr events
  pull_request:
    types:
      - closed

    branches:
      - votes

  # manually trigger workflow
  workflow_dispatch:
    inputs:
      name:
        description: "Enter description"
        required: false
        default: "Describe what you are testing"

jobs:
  count-votes:
    runs-on: ubuntu-latest
    steps:
      # Check out code using git
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0

      # Install node with yarn
      - name: Setup Yarn
        uses: actions/setup-node@v2
      - run: yarn install

      # Run list-reactions.js with Node and pass the authentication token
      - name: Pass the received secret to an action
        run: node .github/actions/list-reactions.js
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
