name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup Yarn
        uses: actions/setup-node@v1
      - run: yarn install

      - name: Setup Hugo 
        uses: peaceiris/actions-hugo@v2
        with:
          # should sync versions with docker-compose .env ala 
          # https://github.com/marketplace/actions/hugo-setup#%EF%B8%8F-read-hugo-version-from-file
          hugo-version: '0.69.2'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master
